// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdsjtbdflemfbqtumyal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkc2p0YmRmbGVtZmJxdHVteWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzgzNzIsImV4cCI6MjA2OTc1NDM3Mn0.eMo2a8xcb-8w3OTjh5HM6XrNiPgySJX_hnMmg3YPzpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});